dist: trusty
sudo: required 

language: c
    
services: 
    - mongodb
    - redis-server

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
      - python3

os:
    - linux

compiler:
    - gcc
    
env:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release
        
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=/usr/bin/gcc-7 && gcc -v && cmake --version; fi
    
    - echo "Configured Downloads"
    - pushd ./cmake/downloads
    - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIGURATION -DCMAKE_CONFIGURATION_TYPES=$BUILD_CONFIGURATION -DHUMMINGBIRD_DOWNLOADS_SILENT=ON
    - popd
    
    - echo "Downloads Dependencies"
    - pushd ./cmake/downloads
    - cmake --build . --config $BUILD_CONFIGURATION
    - popd
    
    - echo "Configured Dependencies"
    - pushd ./cmake/dependencies_unix
    - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIGURATION -DCMAKE_CONFIGURATION_TYPES=$BUILD_CONFIGURATION
    - popd
    
    - echo "Build Dependencies"
    - pushd ./cmake/dependencies_unix
    - cmake --build . --config $BUILD_CONFIGURATION
    - popd
    
    - echo "Configured Solution"
    - pushd ./cmake/hummingbird_unix
    - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIGURATION -DCMAKE_CONFIGURATION_TYPES=$BUILD_CONFIGURATION
    - popd
    
    - echo "Build Solution"
    - pushd ./cmake/hummingbird_unix
    - cmake --build . --config $BUILD_CONFIGURATION
    - popd
    
    - pyenv install 3.6.0
    - pyenv global 3.6.0
    - python --version
    - exec "./bin/hummingbird_unix/Unix Makefiles/hb_grid" &
    - serverpid=$!
    - python "./tests/test.py" "./tests/test.lua"
    - kill -INT $serverpid
    
    - echo "Complete!"
