dist: trusty
sudo: required 

language: c

python:
    - "3.6"
    
services: 
    - mongodb
    - redis-server

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7

os:
    - linux

compiler:
    - gcc
    
env:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release
        
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=/usr/bin/gcc-7 && gcc -v && cmake --version; fi
    
    - echo "Configured Downloads"
    - pushd ./cmake/downloads
    - cmake . -G "Unix Makefiles" -DCMAKE_CONFIGURATION_TYPES=$BUILD_CONFIGURATION -DHUMMINGBIRD_DOWNLOADS_SILENT=ON
    - popd
    
    - echo "Downloads Dependencies"
    - pushd ./cmake/downloads
    - cmake --build . --config $BUILD_CONFIGURATION
    - popd
    
    - echo "Configured Dependencies"
    - pushd ./cmake/dependencies_unix
    - cmake . -G "Unix Makefiles" -DCMAKE_CONFIGURATION_TYPES=$BUILD_CONFIGURATION
    - popd
    
    - echo "Build Dependencies"
    - pushd ./cmake/dependencies_unix
    - cmake --build . --config $BUILD_CONFIGURATION
    - popd
    
    - echo "Configured Solution"
    - pushd ./cmake/hummingbird_unix
    - cmake . -G "Unix Makefiles" -DCMAKE_CONFIGURATION_TYPES=$BUILD_CONFIGURATION
    - popd
    
    - echo "Build Solution"
    - pushd ./cmake/hummingbird_unix
    - cmake --build . --config $BUILD_CONFIGURATION
    - popd
    
    - python --version
    - exec "./bin/hummingbird_unix/Unix Makefiles/$BUILD_CONFIGURATION/hb_grid" & py -3 "./tests/test.py" & wait
    
    - echo "Complete!"
