version: "3"

services:
  hb_grid:
    container_name: hb_grid
    image: takimoysha/hummingfab:v1.debug
    ports:
      - "5555:5555"
    depends_on:
      - "mongo-dev"
      - "redis-dev"

  mongo-dev:
    container_name: mongo-dev
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - /var/tmp/mongo-dev:/data/db

  redis-dev:
    container_name: redis-dev
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - /var/tmp/redis-dev:/data


