FROM debian:latest
LABEL org.opencontainers.image.title = "Hummingfab"
ENV DEBUG=True
  
COPY ./docker_tmp /hummingfab/
# cache (redis)
# EXPOSE 6379
# mongodb
# EXPOSE 27017
# logs
# EXPOSE 5044 


EXPOSE 5555 

WORKDIR /hummingfab/
ENTRYPOINT ["/hummingfab/hb_grid"]
CMD ["--config", "./debug.json"]

# grid
# EXPOSE 5555 

