version: "3"

services:
  hb_grid:
    container_name: hb_grid
    image: takimoysha/hummingfab:v1.debug
    ports:
      - "5555:5555"
    depends_on:
      - "mongo-dev"
      - "redis-dev"
      # - "fluentd-dev"
    # networks:
    #   hb_net:
    #     aliases:
    #       - hb_grid

  mongo-dev:
    container_name: mongo-dev
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - /var/tmp/mongo-dev:/data/db
    # networks:
    #   hm_net:
    #     aliases:
    #       - mongo-dev

  redis-dev:
    container_name: redis-dev
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - /var/tmp/redis-dev:/data
    # networks:
    #   hb_net:
    #     aliases:
    #       - redis-dev

  # fluentd-dev:
  #   container_name: fluentd-dev
  #   image: fluent/fluentd:edge
  #   ports:
  #     - "24224:24224"
  #   volumes:
  #     - /var/tmp/fluentd/:/etc/fluentd/
    # networks:
    #   hb_net:
    #     aliases:
    #       - fluentd-dev
    #

# networks:
#   hb_net:
