FROM debian:latest
LABEL org.opencontainers.image.title = "Hummingfab"
ENV DEBUG=True
  
RUN apt-get update 
RUN apt-get install -y net-tools \
  iputils-ping \
  iproute2 \ 
  strace \
  gnupg \
  wget 


COPY ./docker_tmp /hummingfab/

EXPOSE 5555 

WORKDIR /hummingfab/

RUN chmod +x ./hb_grid ./docker-entrypoint.sh

# ENTRYPOINT ["./hb_grid"]
# CMD ["--config", "./debug.json"]

ENTRYPOINT ["./docker-entrypoint.sh"]
# dev | prod
CMD ["dev"]

