swagger: "2.0"
host: localhost:5555
info:
  description: This is a hummingbird server
  version: "0.1.0"
  title: Hummingbird
  contact:
    email: "irov13@mail.ru"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
tags:
- name: newproject
  description: projects
- name: upload
  description: upload
- name: newuser
  description: newuser
- name: loginuser
  description: login
- name: api
  description: api
schemes:
- http
paths:
  /newproject:
    post:
      tags:
      - newproject
      summary: create new project
      consumes:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              pid:
                type: "string"
        400:
          description: invalid operation
  /upload:
    post:
      tags:
      - upload
      summary: upload script to project
      consumes:
      - multipart/form-data
      parameters:
      - name: pid
        in: formData
        description: Project ID
        required: true
        type: string
      - name: data
        in: formData
        description: file data
        required: true
        type: file
      responses:
        200:
          description: successful operation
          schema:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              revision:
                type: "integer"
                format: "int64"          
        400:
          description: invalid operation
  /newuser:
    post:
      tags:
      - newuser
      summary: create new user project
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        description: new user data
        schema:
          type: object
          required:
            - pid
            - login
            - password
          properties:
            pid:
              type: string
            login:
              type: string
            password:
              type: string
      responses:
        200:
          description: successful operation
          schema:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              token:
                type: "string"
        400:
          description: invalid operation
  /loginuser:
    post:
      tags:
      - loginuser
      summary: login user project
      consumes:
      - application/json
      parameters:
      - in: body
        name: data
        description: login user data
        schema:
          type: object
          required:
            - pid
            - login
            - password
          properties:
            pid:
              type: string
            login:
              type: string
            password:
              type: string
      responses:
        200:
          description: successful operation
          schema:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              token:
                type: "string"
        400:
          description: invalid operation
  /api:
    post:
      tags:
      - api
      summary: call user api
      description: ""
      consumes:
      - application/json
      parameters:
      - name: X-Token
        in: header
        description: user token
        required: true
        type: string
      - name: X-Method
        in: header
        description: api method
        required: true
        type: string
      - in: body
        name: data
        description: login user data
        required: true
        schema:
          type: object       
      responses:
        200:
          description: successful operation
          schema:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              successful:
                type: "boolean"
              data:
                type: "object"      
        400:
          description: invalid operation