set_property(GLOBAL PROPERTY USE_FOLDERS ON)

SET(HUMMINGBIRD_REPOSITORY ${CMAKE_CURRENT_SOURCE_DIR}/../..)
SET(HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/dependencies)
SET(HUMMINGBIRD_SOURCE_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/src)
SET(HUMMINGBIRD_DEPENDENCIES_TEMP_DIRECTORY ${CMAKE_BINARY_DIR}/solutions)

IF(NOT HUMMINGBIRD_INSTALL_PATH)
    SET(HUMMINGBIRD_INSTALL_PATH ${HUMMINGBIRD_REPOSITORY}/bin)
ENDIF()

MESSAGE("HUMMINGBIRD_REPOSITORY: ${HUMMINGBIRD_REPOSITORY}")
MESSAGE("HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY: ${HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY}")
MESSAGE("HUMMINGBIRD_SOURCE_DIRECTORY: ${HUMMINGBIRD_SOURCE_DIRECTORY}")
MESSAGE("HUMMINGBIRD_DEPENDENCIES_TEMP_DIRECTORY: ${HUMMINGBIRD_DEPENDENCIES_TEMP_DIRECTORY}")
MESSAGE("HUMMINGBIRD_INSTALL_PATH: ${HUMMINGBIRD_INSTALL_PATH}")

# input and thirdparty paths
if(UNIX AND NOT ANDROID)
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
elseif(ANDROID)
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
elseif(APPLE)
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
elseif(MINGW)
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
else()
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
endif()

MESSAGE("HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY: ${HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY}")