set_property(GLOBAL PROPERTY USE_FOLDERS ON)

SET(HUMMINGBIRD_REPOSITORY ${CMAKE_CURRENT_SOURCE_DIR}/../..)
SET(HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/dependencies)
SET(HUMMINGBIRD_SOURCE_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/src)
SET(HUMMINGBIRD_DEPENDENCIES_TEMP_DIRECTORY ${CMAKE_BINARY_DIR}/solutions)

IF(NOT HUMMINGBIRD_INSTALL_PATH)
    SET(HUMMINGBIRD_INSTALL_PATH ${HUMMINGBIRD_REPOSITORY}/bin)
ENDIF()

MESSAGE("HUMMINGBIRD_INSTALL_PATH: ${HUMMINGBIRD_INSTALL_PATH}")

if(UNIX AND NOT ANDROID)
    # input and thirdparty paths
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})

    # output paths
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
elseif(ANDROID)
    # input and thirdparty paths
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})

    # output paths
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
elseif(MINGW)
    # input and thirdparty paths
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})

    # output paths
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
else()
    # input and thirdparty paths
    SET(HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
    
    # output paths
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR})   
endif()

MESSAGE("HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY: ${HUMMINGBIRD_DEPENDENCIES_LIBRARY_DIRECTORY}")

MESSAGE("CMAKE_ARCHIVE_OUTPUT_DIRECTORY: ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
MESSAGE("CMAKE_RUNTIME_OUTPUT_DIRECTORY: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")

INCLUDE_DIRECTORIES(${HUMMINGBIRD_SOURCE_DIRECTORY})

SET(HUMMINGBIRD_APPLICATION_DEPENDENCIES)
SET(HUMMINGBIRD_APPLICATION_LINK_LIBRARIES)
