# output paths
if(UNIX AND NOT ANDROID)
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
elseif(ANDROID)
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
elseif(MINGW)
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR}/${CMAKE_BUILD_TYPE})
else()
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${HUMMINGBIRD_REPOSITORY}/lib/${PROJECT_NAME}/${CMAKE_GENERATOR})
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${HUMMINGBIRD_INSTALL_PATH}/${PROJECT_NAME}/${CMAKE_GENERATOR})   
endif()

MESSAGE("CMAKE_ARCHIVE_OUTPUT_DIRECTORY: ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
MESSAGE("CMAKE_RUNTIME_OUTPUT_DIRECTORY: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")

INCLUDE_DIRECTORIES(${HUMMINGBIRD_SOURCE_DIRECTORY})

SET(HUMMINGBIRD_APPLICATION_DEPENDENCIES)
SET(HUMMINGBIRD_APPLICATION_LINK_LIBRARIES)
