CMAKE_MINIMUM_REQUIRED( VERSION 2.6 )

IF(CMAKE_BUILD_TYPE MATCHES "Debug")
    SET(HUMMINGBIRD_BUILD_TYPE_DEBUG 1)
ELSEIF(CMAKE_BUILD_TYPE MATCHES "RelWithDebInfo")
    SET(HUMMINGBIRD_BUILD_TYPE_RELWITHDEBINFO 1)
ELSEIF(CMAKE_BUILD_TYPE MATCHES "Release")
    SET(HUMMINGBIRD_BUILD_TYPE_RELEASE 1)
ENDIF()

MACRO(ADD_FILTER group_name)
    SOURCE_GROUP(${group_name} FILES ${ARGN})
    SET(HUMMINGBIRD_SOURCE_FILES ${HUMMINGBIRD_SOURCE_FILES} ${ARGN})
ENDMACRO()